CREATE TABLE versao_sistema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versao VARCHAR(30) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO versao_sistema (versao, descricao)
VALUES ('0.1.0', 'Fundacao inicial do Sistema de Rastreabilidade');
