CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    tipo VARCHAR(30) NOT NULL,
    controla_lote BOOLEAN NOT NULL,
    controla_validade BOOLEAN NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_produto_codigo UNIQUE (codigo)
);