CREATE TABLE lote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    numero VARCHAR(100) NOT NULL,
    data_fabricacao DATE,
    data_validade DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_lote_produto
        FOREIGN KEY (produto_id) REFERENCES produto(id),

    CONSTRAINT uk_lote_produto_numero
        UNIQUE (produto_id, numero),

    CONSTRAINT ck_lote_datas
        CHECK (
            data_fabricacao IS NULL
            OR data_validade IS NULL
            OR data_validade >= data_fabricacao
        )
);