CREATE TABLE recebimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor VARCHAR(150) NOT NULL,
    documento VARCHAR(100) NOT NULL,
    data_recebimento DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RASCUNHO',
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmado_em TIMESTAMP WITH TIME ZONE,
    confirmado_por BIGINT,

    CONSTRAINT fk_recebimento_usuario
        FOREIGN KEY (confirmado_por) REFERENCES usuario(id),

    CONSTRAINT ck_recebimento_status
        CHECK (status IN ('RASCUNHO', 'CONFIRMADO')),

    CONSTRAINT ck_recebimento_confirmacao
        CHECK (
            (
                status = 'RASCUNHO'
                AND confirmado_em IS NULL
                AND confirmado_por IS NULL
            )
            OR
            (
                status = 'CONFIRMADO'
                AND confirmado_em IS NOT NULL
                AND confirmado_por IS NOT NULL
            )
        )
);

CREATE TABLE recebimento_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recebimento_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    lote_id BIGINT,
    quantidade NUMERIC(19, 6) NOT NULL,

    CONSTRAINT fk_recebimento_item_recebimento
        FOREIGN KEY (recebimento_id) REFERENCES recebimento(id),

    CONSTRAINT fk_recebimento_item_produto
        FOREIGN KEY (produto_id) REFERENCES produto(id),

    CONSTRAINT fk_recebimento_item_lote
        FOREIGN KEY (lote_id) REFERENCES lote(id),

    CONSTRAINT ck_recebimento_item_quantidade
        CHECK (quantidade > 0)
);

CREATE TABLE movimentacao_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recebimento_item_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    lote_id BIGINT,
    quantidade NUMERIC(19, 6) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    registrado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    registrado_por BIGINT NOT NULL,

    CONSTRAINT fk_movimentacao_recebimento_item
        FOREIGN KEY (recebimento_item_id) REFERENCES recebimento_item(id),

    CONSTRAINT fk_movimentacao_produto
        FOREIGN KEY (produto_id) REFERENCES produto(id),

    CONSTRAINT fk_movimentacao_lote
        FOREIGN KEY (lote_id) REFERENCES lote(id),

    CONSTRAINT fk_movimentacao_usuario
        FOREIGN KEY (registrado_por) REFERENCES usuario(id),

    CONSTRAINT uk_movimentacao_recebimento_item
        UNIQUE (recebimento_item_id),

    CONSTRAINT ck_movimentacao_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT ck_movimentacao_tipo
        CHECK (tipo = 'ENTRADA')
);

CREATE INDEX idx_recebimento_item_recebimento
    ON recebimento_item(recebimento_id);

CREATE INDEX idx_movimentacao_produto_lote
    ON movimentacao_estoque(produto_id, lote_id);