CREATE TABLE expedicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario VARCHAR(150) NOT NULL,
    documento VARCHAR(100) NOT NULL,
    data_expedicao DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RASCUNHO',
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmado_em TIMESTAMP WITH TIME ZONE,
    confirmado_por BIGINT,

    CONSTRAINT fk_expedicao_usuario
        FOREIGN KEY (confirmado_por) REFERENCES usuario(id),

    CONSTRAINT ck_expedicao_status
        CHECK (status IN ('RASCUNHO', 'CONFIRMADO')),

    CONSTRAINT ck_expedicao_confirmacao
        CHECK (
            (
                status = 'RASCUNHO'
                AND confirmado_em IS NULL
                AND confirmado_por IS NULL
            )
            OR
            (
                status = 'CONFIRMADO'
                AND confirmado_em IS NOT NULL
                AND confirmado_por IS NOT NULL
            )
        )
);

CREATE TABLE expedicao_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expedicao_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    lote_id BIGINT,
    quantidade NUMERIC(19, 6) NOT NULL,

    CONSTRAINT fk_expedicao_item_expedicao
        FOREIGN KEY (expedicao_id) REFERENCES expedicao(id),

    CONSTRAINT fk_expedicao_item_produto
        FOREIGN KEY (produto_id) REFERENCES produto(id),

    CONSTRAINT fk_expedicao_item_lote
        FOREIGN KEY (lote_id) REFERENCES lote(id),

    CONSTRAINT ck_expedicao_item_quantidade
        CHECK (quantidade > 0)
);

CREATE INDEX idx_expedicao_item_expedicao
    ON expedicao_item(expedicao_id);

ALTER TABLE movimentacao_estoque
    ALTER COLUMN recebimento_item_id DROP NOT NULL;

ALTER TABLE movimentacao_estoque
    ADD COLUMN expedicao_item_id BIGINT;

ALTER TABLE movimentacao_estoque
    ADD CONSTRAINT fk_movimentacao_expedicao_item
        FOREIGN KEY (expedicao_item_id) REFERENCES expedicao_item(id);

ALTER TABLE movimentacao_estoque
    ADD CONSTRAINT uk_movimentacao_expedicao_item
        UNIQUE (expedicao_item_id);

ALTER TABLE movimentacao_estoque
    DROP CONSTRAINT ck_movimentacao_tipo;

ALTER TABLE movimentacao_estoque
    ADD CONSTRAINT ck_movimentacao_tipo
        CHECK (tipo IN ('ENTRADA', 'SAIDA'));

ALTER TABLE movimentacao_estoque
    ADD CONSTRAINT ck_movimentacao_origem
        CHECK (
            (
                tipo = 'ENTRADA'
                AND recebimento_item_id IS NOT NULL
                AND expedicao_item_id IS NULL
            )
            OR
            (
                tipo = 'SAIDA'
                AND expedicao_item_id IS NOT NULL
                AND recebimento_item_id IS NULL
            )
        );