CREATE TABLE perfil_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    sistema BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT uk_perfil_acesso_codigo UNIQUE (codigo)
);

CREATE TABLE permissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL,
    descricao VARCHAR(200) NOT NULL,

    CONSTRAINT uk_permissao_codigo UNIQUE (codigo)
);

CREATE TABLE perfil_permissao (
    perfil_id BIGINT NOT NULL,
    permissao_id BIGINT NOT NULL,

    CONSTRAINT pk_perfil_permissao
        PRIMARY KEY (perfil_id, permissao_id),

    CONSTRAINT fk_perfil_permissao_perfil
        FOREIGN KEY (perfil_id) REFERENCES perfil_acesso(id),

    CONSTRAINT fk_perfil_permissao_permissao
        FOREIGN KEY (permissao_id) REFERENCES permissao(id)
);

CREATE TABLE usuario_perfil (
    usuario_id BIGINT NOT NULL,
    perfil_id BIGINT NOT NULL,

    CONSTRAINT pk_usuario_perfil
        PRIMARY KEY (usuario_id, perfil_id),

    CONSTRAINT fk_usuario_perfil_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(id),

    CONSTRAINT fk_usuario_perfil_perfil
        FOREIGN KEY (perfil_id) REFERENCES perfil_acesso(id)
);

CREATE INDEX idx_perfil_permissao_permissao
    ON perfil_permissao(permissao_id);

CREATE INDEX idx_usuario_perfil_perfil
    ON usuario_perfil(perfil_id);

INSERT INTO perfil_acesso (codigo, nome, sistema)
VALUES
    ('DIRETORIA', 'Diretoria', TRUE),
    ('ADMINISTRADOR', 'Administrador', TRUE),
    ('RESPONSAVEL_TECNICO', 'Responsável Técnico', TRUE),
    ('QUALIDADE', 'Qualidade', TRUE),
    ('ESTOQUE', 'Estoque', TRUE),
    ('CONSULTA', 'Consulta', TRUE),
    ('COMPRAS', 'Compras', TRUE),
    ('VENDAS', 'Vendas', TRUE),
    ('FINANCEIRO', 'Financeiro', TRUE),
    ('LOGISTICA', 'Logística', TRUE),
    ('TI', 'TI', TRUE);

INSERT INTO usuario_perfil (usuario_id, perfil_id)
SELECT u.id, p.id
FROM usuario u
JOIN perfil_acesso p ON p.codigo = u.perfil;